version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - CI=true
    command: npm run start:ci
    volumes:
      - ./:/app
      - /app/node_modules