name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build the Docker image
      run: |
        cd todo-list-frontend
        docker-compose build

    - name: Run Docker Compose
      run: |
        cd todo-list-frontend
        docker-compose up -d

    - name: Wait for the app to be ready
      run: |
        cd todo-list-frontend
        max_retries=60
        counter=0
        container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker-compose ps -q react-app))
        echo "Container IP: $container_ip"
        until curl -s http://$container_ip:3000 > /dev/null || [ $counter -eq $max_retries ]
        do
          echo "Waiting for app to be ready... (Attempt $counter)"
          docker-compose logs --tail=50 react-app
          sleep 10
          ((counter++))
        done
        if [ $counter -eq $max_retries ]; then
          echo "App failed to start in time"
          docker-compose logs
          exit 1
        else
          echo "App is ready!"
          curl -v http://$container_ip:3000
        fi

    - name: Run tests
      run: |
        cd todo-list-frontend
        docker-compose exec -T react-app npm test

    - name: Stop containers
      if: always()
      run: |
        cd todo-list-frontend
        docker-compose down